
%% =======================================
[N,G,R,clean_mini,av]=NSNA_bootstrap(LCRA.early.fast.mini);
LCRA.early.fast.N=N;
LCRA.early.fast.G=G;
LCRA.early.fast.R=R;
LCRA.early.fast.clean=clean_mini;
LCRA.early.fast.av=av;
1

[N,G,R,clean_mini,av]=NSNA_bootstrap(LCRA.early.slow.mini);
LCRA.early.slow.N=N;
LCRA.early.slow.G=G;
LCRA.early.slow.R=R;
LCRA.early.slow.clean=clean_mini;
LCRA.early.slow.av=av;
2

[N,G,R,clean_mini,av]=NSNA_bootstrap(LCRA.late.fast.mini);
LCRA.late.fast.N=N;
LCRA.late.fast.G=G;
LCRA.late.fast.R=R;
LCRA.late.fast.clean=clean_mini;
LCRA.late.fast.av=av;
3

[N,G,R,clean_mini,av]=NSNA_bootstrap(LCRA.late.slow.mini);
LCRA.late.slow.N=N;
LCRA.late.slow.G=G;
LCRA.late.slow.R=R;
LCRA.late.slow.clean=clean_mini;
LCRA.late.slow.av=av;
4

%% =======================================
[N,G,R,clean_mini,av]=NSNA_bootstrap(cn21_ef);
CN21.early.fast.mini=cn21_ef;
CN21.early.fast.N=N;
CN21.early.fast.G=G;
CN21.early.fast.R=R;
CN21.early.fast.clean=clean_mini;
CN21.early.fast.av=av;
5
[N,G,R,clean_mini,av]=NSNA_bootstrap(cn21_es);
CN21.early.slow.mini=cn21_es;
CN21.early.slow.N=N;
CN21.early.slow.G=G;
CN21.early.slow.R=R;
CN21.early.slow.clean=clean_mini;
CN21.early.slow.av=av;
6
[N,G,R,clean_mini,av]=NSNA_bootstrap(cn21_lf);
CN21.late.fast.mini=cn21_lf;
CN21.late.fast.N=N;
CN21.late.fast.G=G;
CN21.late.fast.R=R;
CN21.late.fast.clean=clean_mini;
CN21.late.fast.av=av;
7
[N,G,R,clean_mini,av]=NSNA_bootstrap(cn21_ls);
CN21.late.slow.mini=cn21_ls;
CN21.late.slow.N=N;
CN21.late.slow.G=G;
CN21.late.slow.R=R;
CN21.late.slow.clean=clean_mini;
CN21.late.slow.av=av;
8
%% =======================================
[N,G,R,clean_mini,av]=NSNA_bootstrap(scr_ef);
SCR.early.fast.mini=scr_ef;
SCR.early.fast.N=N;
SCR.early.fast.G=G;
SCR.early.fast.R=R;
SCR.early.fast.clean=clean_mini;
SCR.early.fast.av=av;
9
[N,G,R,clean_mini,av]=NSNA_bootstrap(scr_es);
SCR.early.slow.mini=scr_es;
SCR.early.slow.N=N;
SCR.early.slow.G=G;
SCR.early.slow.R=R;
SCR.early.slow.clean=clean_mini;
SCR.early.slow.av=av;
10
[N,G,R,clean_mini,av]=NSNA_bootstrap(scr_lf);
SCR.late.fast.mini=scr_lf;
SCR.late.fast.N=N;
SCR.late.fast.G=G;
SCR.late.fast.R=R;
SCR.late.fast.clean=clean_mini;
SCR.late.fast.av=av;
11
[N,G,R,clean_mini,av]=NSNA_bootstrap(scr_ls);
SCR.late.slow.mini=scr_ls;
SCR.late.slow.N=N;
SCR.late.slow.G=G;
SCR.late.slow.R=R;
SCR.late.slow.clean=clean_mini;
SCR.late.slow.av=av;
12